#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
pushd $SCRIPT_DIR

ASEPRITE=/Applications/Aseprite.app/Contents/MacOS/aseprite

$ASEPRITE -b player.aseprite --sheet player.png --scale 2 --split-tags
$ASEPRITE -b flag.aseprite --sheet flag.png --scale 2 --split-tags
$ASEPRITE -b link.aseprite --sheet link.png --scale 2 --split-tags
$ASEPRITE -b platform.aseprite --sheet platform.png --scale 2 --split-tags
$ASEPRITE -b wall.aseprite --sheet wall.png --scale 2 --split-tags

$ASEPRITE -b logo.aseprite --sheet logo.png --scale 2
$ASEPRITE -b hurt.aseprite --sheet hurt.png --scale 2

popd $SCRIPT_DIR
